### ISSUE TITLE
Container image jim:2.1.0 not working

### ISSUE THREAD

**Issue by tjarbo** [p-fruck/jim#22]
```sh
[2021-05-21 12:22:11] [backend] [[32mINFO[39m]: joining conference XXXXXXX
node:fs:1072
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, scandir '/app/dist/commands/local'
    at Object.readdirSync (node:fs:1072:3)
    at registerDirectory (/app/dist/command.service.js:38:14)
    at Function.init (/app/dist/command.service.js:43:13)
    at Function.init (/app/dist/jitsi-bot.js:47:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async startBrowser (/app/dist/index.js:24:5) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/app/dist/commands/local'
}
```

**Comment by p-fruck** [comment]
Thanks for creating the issue! This was due to a missing directory, fixed with 6bbca96
